### PR TITLE
[URGENT] [MAJOR] [APP-BREAKING] GRAMMAR FIX

### PR DESCRIPTION
**Pull request by jeuxjeux20**
pls fix

### CODE REVIEW

**Comment by jeuxjeux20** [comment]
yay

**Comment by jeuxjeux20** [comment]
i luv u

**Comment by jeuxjeux20** [comment]
u r my best friend

**Comment by jeuxjeux20** [comment]
thx

**Comment by FireC123** [comment]
;-;

**Comment by FireC123** [comment]
what about me

**Comment by FireC123** [comment]
i kms

**Comment by jeuxjeux20** [comment]
nu

**Comment by jeuxjeux20** [comment]
u r the same

**Comment by jeuxjeux20** [comment]
o and wtf

**Comment by jeuxjeux20** [comment]
github can be used as a mini discord

**Comment by FireC123** [comment]
yea

**Comment by jeuxjeux20** [comment]
noice

**Pull request merged**
